platforms:
    - {
        name: arm,
        runner_name: runners.arm,
        gcc481: arm-none-eabi-gcc,
        compiler_whitelist: [gcc481]
      }

benchmarks:
    - {
        name: 2dfir
        # Allow any compiler
      }

compilers:
    - {
        name: gcc481,
        flags:
            [-ftree-dominator-opts,
             -ftree-loop-optimize,
             -fomit-frame-pointer,
             -fdce]
      }

database:
    # username:
    # password:
    # socket:
    database: db/development.sqlite3
